name: CoAP-Link Development Deployment Routine

on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_LOGIN_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t datafarm/coap-link:development .

      - name: Push Docker Image to Docker Hub
        run: docker push datafarm/coap-link:development

  deploy-to-dev:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - name: SSH into EC2 and deploy Docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 5823
          script: |
            echo "Starting deployment..."

            # Stop and remove any old containers
            docker stop coap-link || true
            docker rm coap-link || true

            # Remove unused images
            docker image prune -f || true

            # Pull the latest image from Docker Hub
            docker pull datafarm/coap-link:development

            # Run container with host networking for lowest latency
            docker run -d \
              --name coap-link \
              --network host \
              datafarm/coap-link:development

            echo "✅ Deployment completed successfully!"